/*
-- Query: select * from redcap_entity_test_site
where project_id = 8316 and id = 15
LIMIT 0, 5000

-- Date: 2020-04-21 17:02
*/
INSERT INTO `redcap_entity_test_site` (`created`,`updated`,`site_long_name`,`site_short_name`,`site_address`,`site_appointment_duration`,`open_time`,`close_time`,`closed_days`,`horizon_days`,`testing_type`,`project_id`,`start_date`,`custom_daily_schedule`,`use_custom_daily_schedule`) VALUES (1587089441,1587502827,'PK Yonge School','1','1600 Pennsylvania Ave., Washington, DC 12345','30','12:30','13:00','6','40','swabandserum',1,1587960000,'{\r\n    \"Monday\": {\r\n        \"open\": \"12:30\",\r\n        \"close\": \"13:00\"\r\n    },\r\n    \"Tuesday\": {\r\n        \"open\": \"\",\r\n        \"close\": \"\"\r\n    },\r\n    \"Wednesday\": {\r\n        \"open\": \"12:30\",\r\n        \"close\": \"13:00\"\r\n    },\r\n    \"Thursday\": {\r\n        \"open\": \"\",\r\n        \"close\": \"\"\r\n    },\r\n    \"Friday\": {\r\n        \"open\": \"12:30\",\r\n        \"close\": \"13:00\"\r\n    },\r\n    \"Saturday\": {\r\n        \"open\": \"\",\r\n        \"close\": \"\"\r\n    },\r\n    \"Sunday\": {\r\n        \"open\": \"\",\r\n        \"close\": \"\"\r\n    }\r\n}','1');
INSERT INTO `redcap_entity_test_site` (`created`,`updated`,`site_long_name`,`site_short_name`,`site_address`,`site_appointment_duration`,`open_time`,`close_time`,`closed_days`,`horizon_days`,`testing_type`,`project_id`,`start_date`,`custom_daily_schedule`,`use_custom_daily_schedule`) VALUES (1587089441,1587502827,'PK Yonge School','2','1600 Pennsylvania Ave., Washington, DC 12345','30','12:30','13:00','6','40','swabandserum',1,1587960000,'{\r\n    \"Monday\": {\r\n        \"open\": \"12:30\",\r\n        \"close\": \"13:00\"\r\n    },\r\n    \"Tuesday\": {\r\n        \"open\": \"\",\r\n        \"close\": \"\"\r\n    },\r\n    \"Wednesday\": {\r\n        \"open\": \"12:30\",\r\n        \"close\": \"13:00\"\r\n    },\r\n    \"Thursday\": {\r\n        \"open\": \"\",\r\n        \"close\": \"\"\r\n    },\r\n    \"Friday\": {\r\n        \"open\": \"12:30\",\r\n        \"close\": \"13:00\"\r\n    },\r\n    \"Saturday\": {\r\n        \"open\": \"\",\r\n        \"close\": \"\"\r\n    },\r\n    \"Sunday\": {\r\n        \"open\": \"\",\r\n        \"close\": \"\"\r\n    }\r\n}','1');
INSERT INTO `redcap_entity_test_site` (`created`,`updated`,`site_long_name`,`site_short_name`,`site_address`,`site_appointment_duration`,`open_time`,`close_time`,`closed_days`,`horizon_days`,`testing_type`,`project_id`,`start_date`,`custom_daily_schedule`,`use_custom_daily_schedule`) VALUES (1587089441,1587502827,'PK Yonge School','3','1600 Pennsylvania Ave., Washington, DC 12345','30','12:30','13:00','6','40','swabandserum',1,1587960000,'{\r\n    \"Monday\": {\r\n        \"open\": \"12:30\",\r\n        \"close\": \"13:00\"\r\n    },\r\n    \"Tuesday\": {\r\n        \"open\": \"\",\r\n        \"close\": \"\"\r\n    },\r\n    \"Wednesday\": {\r\n        \"open\": \"12:30\",\r\n        \"close\": \"13:00\"\r\n    },\r\n    \"Thursday\": {\r\n        \"open\": \"\",\r\n        \"close\": \"\"\r\n    },\r\n    \"Friday\": {\r\n        \"open\": \"12:30\",\r\n        \"close\": \"13:00\"\r\n    },\r\n    \"Saturday\": {\r\n        \"open\": \"\",\r\n        \"close\": \"\"\r\n    },\r\n    \"Sunday\": {\r\n        \"open\": \"\",\r\n        \"close\": \"\"\r\n    }\r\n}','1');
INSERT INTO `redcap_entity_test_site` (`created`,`updated`,`site_long_name`,`site_short_name`,`site_address`,`site_appointment_duration`,`open_time`,`close_time`,`closed_days`,`horizon_days`,`testing_type`,`project_id`,`start_date`,`custom_daily_schedule`,`use_custom_daily_schedule`) VALUES (1587089441,1587502827,'PK Yonge School','4','1600 Pennsylvania Ave., Washington, DC 12345','30','12:30','13:00','6','40','swabandserum',1,1587960000,'{\r\n    \"Monday\": {\r\n        \"open\": \"12:30\",\r\n        \"close\": \"13:00\"\r\n    },\r\n    \"Tuesday\": {\r\n        \"open\": \"\",\r\n        \"close\": \"\"\r\n    },\r\n    \"Wednesday\": {\r\n        \"open\": \"12:30\",\r\n        \"close\": \"13:00\"\r\n    },\r\n    \"Thursday\": {\r\n        \"open\": \"\",\r\n        \"close\": \"\"\r\n    },\r\n    \"Friday\": {\r\n        \"open\": \"12:30\",\r\n        \"close\": \"13:00\"\r\n    },\r\n    \"Saturday\": {\r\n        \"open\": \"\",\r\n        \"close\": \"\"\r\n    },\r\n    \"Sunday\": {\r\n        \"open\": \"\",\r\n        \"close\": \"\"\r\n    }\r\n}','1');
INSERT INTO `redcap_entity_test_site` (`created`,`updated`,`site_long_name`,`site_short_name`,`site_address`,`site_appointment_duration`,`open_time`,`close_time`,`closed_days`,`horizon_days`,`testing_type`,`project_id`,`start_date`,`custom_daily_schedule`,`use_custom_daily_schedule`) VALUES (1587089441,1587502827,'PK Yonge School','5','1600 Pennsylvania Ave., Washington, DC 12345','30','12:30','13:00','6','40','swabandserum',1,1587960000,'{\r\n    \"Monday\": {\r\n        \"open\": \"12:30\",\r\n        \"close\": \"13:00\"\r\n    },\r\n    \"Tuesday\": {\r\n        \"open\": \"\",\r\n        \"close\": \"\"\r\n    },\r\n    \"Wednesday\": {\r\n        \"open\": \"12:30\",\r\n        \"close\": \"13:00\"\r\n    },\r\n    \"Thursday\": {\r\n        \"open\": \"\",\r\n        \"close\": \"\"\r\n    },\r\n    \"Friday\": {\r\n        \"open\": \"12:30\",\r\n        \"close\": \"13:00\"\r\n    },\r\n    \"Saturday\": {\r\n        \"open\": \"\",\r\n        \"close\": \"\"\r\n    },\r\n    \"Sunday\": {\r\n        \"open\": \"\",\r\n        \"close\": \"\"\r\n    }\r\n}','1');
INSERT INTO `redcap_entity_test_site` (`created`,`updated`,`site_long_name`,`site_short_name`,`site_address`,`site_appointment_duration`,`open_time`,`close_time`,`closed_days`,`horizon_days`,`testing_type`,`project_id`,`start_date`,`custom_daily_schedule`,`use_custom_daily_schedule`) VALUES (1587089441,1587502827,'PK Yonge School','6','1600 Pennsylvania Ave., Washington, DC 12345','30','12:30','13:00','6','40','swabandserum',1,1587960000,'{\r\n    \"Monday\": {\r\n        \"open\": \"12:30\",\r\n        \"close\": \"13:00\"\r\n    },\r\n    \"Tuesday\": {\r\n        \"open\": \"\",\r\n        \"close\": \"\"\r\n    },\r\n    \"Wednesday\": {\r\n        \"open\": \"12:30\",\r\n        \"close\": \"13:00\"\r\n    },\r\n    \"Thursday\": {\r\n        \"open\": \"\",\r\n        \"close\": \"\"\r\n    },\r\n    \"Friday\": {\r\n        \"open\": \"12:30\",\r\n        \"close\": \"13:00\"\r\n    },\r\n    \"Saturday\": {\r\n        \"open\": \"\",\r\n        \"close\": \"\"\r\n    },\r\n    \"Sunday\": {\r\n        \"open\": \"\",\r\n        \"close\": \"\"\r\n    }\r\n}','1');

update redcap_entity_test_site
set project_id = 2
where project_id = 1;
COMMIT;
